// User Schema
export const UserSchema = {
  profile_id: { type: String, required: true, unique: true }, // SHA256 hash of phone
  name: { type: String, required: true },
  phone: { type: String, required: true, unique: true, match: /^[0-9]{10}$/ },
  balance: { type: Number, default: 0 }, // in paise (₹1 = 100 paise)
  initial_balance: { type: Number, default: 0 },
  
  // Device info
  device_ids: [String], // MAC addresses of associated devices
  last_device: String,
  
  // Sync info
  last_sync: { type: Date, default: Date.now },
  last_full_sync: Date,
  sync_count: { type: Number, default: 0 },
  
  // Timestamps
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now }
};

// Transaction Schema
export const TransactionSchema = {
  // Local identifiers
  tx_id: { type: String, required: true, unique: true }, // Generated by ESP32
  local_timestamp: { type: Number, required: true }, // millis() from ESP32
  
  // User info
  sender_profile_id: { type: String, required: true, index: true },
  receiver_profile_id: { type: String, required: true, index: true },
  sender_phone: { type: String, required: true },
  receiver_phone: { type: String, required: true },
  
  // Transaction details
  amount_paise: { type: Number, required: true },
  amount_rupees: { type: Number, required: true },
  type: { 
    type: String, 
    required: true,
    enum: ['send', 'receive', 'topup', 'refund', 'kirana', 'adjustment']
  },
  mode: {
    type: String,
    required: true,
    enum: ['card', 'online', 'offline', 'qrcode']
  },
  status: {
    type: String,
    required: true,
    enum: ['pending', 'processing', 'completed', 'failed', 'refunded'],
    default: 'pending'
  },
  description: String,
  
  // Device info
  device_id: String, // ESP32 MAC address
  device_mac: String,
  
  // Sync info
  synced_at: { type: Date, default: Date.now },
  needs_sync: { type: Boolean, default: false },
  sync_attempts: { type: Number, default: 0 },
  
  // Reconciliation
  reconciled: { type: Boolean, default: false },
  reconciliation_note: String,
  
  // Timestamps
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now }
};

// Pending Sync Schema (for offline transactions)
export const PendingSyncSchema = {
  tx_id: { type: String, required: true, unique: true },
  profile_id: { type: String, required: true, index: true },
  data: { type: Object, required: true }, // Full transaction data
  created_at: { type: Date, default: Date.now },
  retry_count: { type: Number, default: 0 },
  last_attempt: Date
};